- name:  Extra Packages for Enterprise Linux (or EPEL) is present
  yum: 
     name: epel-release 
     state: latest  
  tags: [common]

- name: CentOS files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ centos_files }}"
  tags: [common]

- name: CentOS Daemon is reloaded
  command: systemctl daemon-reload
  tags: [common]

- name: Centos sshd service is restarted
  service:
    name: sshd
    state: restarted
  tags: [common]
